### ISSUE TITLE
Android runtimes. Unable to build

### ISSUE THREAD

**Issue by SangameswaranRS** [marykdb/rocksdb-multiplatform#2]
Getting ```Unsupported class file major version 59``` on SDK 31

**Comment by SangameswaranRS** [comment]
Think its due to high targeting on the JVM.
Is JVM 11 supported?

**Comment by jurmous** [comment]
I made a mistake with the Android publishing while doing a quick upgrade of the dependencies. The .so files were in a wrong directory due to a change in Android its build system.

I have published a new version as `6.20.4-2` of both `rocksdb-multiplatform` and `rocksdb-android` projects, which should work again on Android.

**Comment by SangameswaranRS** [comment]
Oh, will check then. @jurmous , Keep up the great work.
